# Generated by Django 4.1.7 on 2023-06-01 13:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('construct', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cassetteassembly',
            name='workstation',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='cassetteassembly_workstation', to='construct.workstation'),
        ),
    ]
