# Generated by Django 4.1.7 on 2023-06-01 13:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('construct', '0002_cassetteassembly_workstation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cassetteassembly',
            name='workstation',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='construct.workstation'),
        ),
    ]
