# Generated by Django 4.1.7 on 2023-06-01 14:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('construct', '0003_alter_cassetteassembly_workstation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cassetteassembly',
            name='workstation',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='work', to='construct.workstation'),
        ),
    ]
