# Generated by Django 4.1.7 on 2023-06-01 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('construct', '0005_alter_cassetteassembly_cassette'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cassetteassembly',
            name='layer',
            field=models.IntegerField(default=1),
        ),
    ]
