# Generated by Django 4.1.7 on 2023-06-13 12:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('construct', '0006_alter_cassetteassembly_layer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cassetteassembly',
            name='step',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='step', to='construct.step'),
        ),
    ]
