# Generated by Django 4.1.7 on 2023-03-22 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='VisualInspection',
            fields=[
                ('record_id', models.IntegerField(primary_key=True, serialize=False)),
                ('pcb_id', models.IntegerField(blank=True)),
                ('test_date', models.DateTimeField(blank=True)),
                ('tested_by', models.CharField(blank=True, max_length=20)),
                ('stage', models.CharField(blank=True, max_length=20)),
                ('comments', models.CharField(blank=True, max_length=50)),
                ('flatness', models.CharField(blank=True, max_length=10)),
                ('thikness', models.CharField(blank=True, max_length=20)),
                ('plating_bga', models.CharField(blank=True, max_length=10)),
                ('plating_holes', models.CharField(blank=True, max_length=10)),
                ('mask_aligment', models.CharField(blank=True, max_length=10)),
                ('glue', models.CharField(blank=True, max_length=10)),
                ('accepted', models.CharField(blank=True, max_length=20)),
            ],
            options={
                'db_table': 'qc_pcb_visual',
            },
        ),
    ]
