# Generated by Django 4.1.7 on 2023-03-29 16:12

import base.models
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ConditionsDataSets',
            fields=[
                ('condition_data_set_id', models.IntegerField(primary_key=True, serialize=False)),
                ('record_del_flag_time', models.DateTimeField()),
                ('record_del_flag_user', models.CharField(max_length=50)),
                ('extension_table_name', models.CharField(max_length=30)),
                ('data_file_name', models.CharField(max_length=4000)),
                ('image_file_name', models.CharField(max_length=4000)),
                ('version', models.CharField(max_length=40)),
                ('create_timestamp', models.DateTimeField()),
                ('created_by_user', models.CharField(max_length=50)),
                ('subversion', models.IntegerField()),
                ('number_of_events_in_set', models.IntegerField()),
                ('set_number', models.IntegerField()),
                ('set_begin_timestamp', models.DateTimeField()),
                ('set_end_timestamp', models.DateTimeField()),
                ('set_status', models.IntegerField()),
                ('is_record_deleted', models.CharField(default='F', max_length=1)),
                ('record_insertion_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('record_insertion_user', models.TextField(max_length=50)),
                ('aggregated_cond_data_set', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='base.conditionsdatasets')),
            ],
        ),
        migrations.CreateModel(
            name='CondRun',
            fields=[
                ('cond_run_id', models.IntegerField(primary_key=True, serialize=False)),
                ('run_begin_timestamp', models.DateField()),
                ('run_name', models.CharField(max_length=255)),
                ('run_end_timestamp', models.DateField()),
                ('initiated_by_user', models.CharField(max_length=80)),
                ('location', models.CharField(max_length=40)),
                ('run_type', models.CharField(max_length=120)),
                ('run_number', models.IntegerField()),
                ('is_record_deleted', models.CharField(default='F', max_length=1)),
                ('record_insertion_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('record_insertion_user', models.TextField(max_length=50)),
                ('record_lastupdate_time', models.DateTimeField()),
                ('record_lastupdate_user', models.TextField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Institution',
            fields=[
                ('institution_id', models.AutoField(primary_key=True, serialize=False)),
                ('institute_code', models.IntegerField()),
                ('name', models.TextField(max_length=256)),
                ('town', models.TextField(max_length=128)),
                ('country', models.TextField(max_length=3)),
                ('is_record_deleted', models.CharField(default='F', max_length=1)),
                ('record_insertion_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('record_insertion_user', models.TextField(max_length=50)),
                ('record_lastupdate_time', models.DateTimeField()),
                ('record_lastupdate_user', models.TextField(max_length=50)),
                ('comment_description', models.TextField(max_length=4000)),
            ],
            options={
                'abstract': False,
            },
            bases=(models.Model, base.models.Base),
        ),
        migrations.CreateModel(
            name='KindOfCondition',
            fields=[
                ('kind_of_condition_id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=40)),
                ('extension_table_name', models.CharField(max_length=30)),
                ('is_record_deleted', models.CharField(default='F', max_length=1)),
                ('record_insertion_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('record_insertion_user', models.TextField(max_length=50)),
                ('record_lastupdate_time', models.DateTimeField()),
                ('record_lastupdate_user', models.TextField(max_length=50)),
                ('category_name', models.CharField(max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='KindOfPart',
            fields=[
                ('kind_of_part_id', models.IntegerField(primary_key=True, serialize=False)),
                ('is_imaginary_part', models.CharField(default='F', max_length=1)),
                ('display_name', models.CharField(max_length=40)),
                ('is_detector_part', models.CharField(default='F', max_length=1)),
                ('extension_table_name', models.TextField(default='PARTS', max_length=30)),
                ('lpname', models.TextField(max_length=24)),
                ('is_record_deleted', models.CharField(default='F', max_length=1)),
                ('record_insertion_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('record_insertion_user', models.TextField(max_length=50)),
                ('record_lastupdate_time', models.DateTimeField()),
                ('record_lastupdate_user', models.TextField(max_length=50)),
                ('comment_description', models.TextField(max_length=4000)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('location_id', models.AutoField(primary_key=True, serialize=False)),
                ('location_name', models.TextField(max_length=40)),
                ('is_record_deleted', models.CharField(default='F', max_length=1)),
                ('record_insertion_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('record_insertion_user', models.TextField(max_length=50)),
                ('record_lastupdate_time', models.DateTimeField()),
                ('record_lastupdate_user', models.TextField(max_length=50)),
                ('comment_description', models.TextField(max_length=4000)),
                ('institution', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.institution')),
            ],
        ),
        migrations.CreateModel(
            name='Manufacturer',
            fields=[
                ('manufacturer_id', models.IntegerField(primary_key=True, serialize=False)),
                ('manufacturer_name', models.TextField(max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='Subdetector',
            fields=[
                ('subdetector_id', models.AutoField(primary_key=True, serialize=False)),
                ('subdetector_name', models.TextField(max_length=40)),
            ],
            options={
                'abstract': False,
            },
            bases=(models.Model, base.models.Base),
        ),
        migrations.CreateModel(
            name='Part',
            fields=[
                ('part_id', models.AutoField(primary_key=True, serialize=False)),
                ('name_label', models.TextField(blank=True, max_length=40, null=True)),
                ('serial_number', models.TextField(blank=True, max_length=40, null=True)),
                ('barcode', models.TextField(blank=True, max_length=40, null=True, unique=True)),
                ('version', models.TextField(blank=True, max_length=40, null=True)),
                ('installed_date', models.DateField(blank=True)),
                ('installed_by_user', models.TextField(blank=True, max_length=40, null=True)),
                ('removed_date', models.DateField(blank=True, null=True)),
                ('removed_by_user', models.TextField(blank=True, max_length=40, null=True)),
                ('extension_table_name', models.TextField(blank=True, max_length=30)),
                ('record_insertion_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('record_insertion_user', models.TextField(max_length=50)),
                ('record_lastupdate_time', models.DateTimeField()),
                ('record_lastupdate_user', models.TextField(max_length=50)),
                ('comment_description', models.TextField(blank=True, max_length=4000)),
                ('is_record_deleted', models.CharField(default='F', max_length=1)),
                ('kind_of_part', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='parts', to='base.kindofpart')),
                ('location', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='parts', to='base.location')),
                ('manufacturer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='base.manufacturer')),
            ],
        ),
        migrations.AddField(
            model_name='kindofpart',
            name='manufacturer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='base.manufacturer'),
        ),
        migrations.AddField(
            model_name='kindofpart',
            name='subdetector',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='base.subdetector'),
        ),
        migrations.CreateModel(
            name='HGCROCTest',
            fields=[
                ('record_id', models.IntegerField(primary_key=True, serialize=False)),
                ('hgcroc_status', models.CharField(max_length=12)),
                ('comments', models.CharField(max_length=100)),
                ('condition_data_set_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='base.conditionsdatasets')),
            ],
        ),
        migrations.AddField(
            model_name='conditionsdatasets',
            name='kind_of_condition',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='base.kindofcondition'),
        ),
        migrations.AddField(
            model_name='conditionsdatasets',
            name='part',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='conditions', to='base.part'),
        ),
    ]
