# Generated by Django 4.1.7 on 2023-03-22 21:03

import base.models
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='KindOfCondition',
            fields=[
                ('kind_of_condition_id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=40)),
                ('extension_table_name', models.CharField(max_length=30)),
                ('is_record_deleted', models.CharField(default='F', max_length=1)),
                ('record_insertion_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('record_insertion_user', models.TextField(max_length=50)),
                ('record_lastupdate_time', models.DateTimeField()),
                ('record_lastupdate_user', models.TextField(max_length=50)),
                ('category_name', models.CharField(max_length=40)),
            ],
            options={
                'db_table': 'CMS_HGC_CORE_COND.KINDS_OF_CONDITIONS',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='KindOfPart',
            fields=[
                ('kind_of_part_id', models.IntegerField(primary_key=True, serialize=False)),
                ('is_imaginary_part', models.CharField(default='F', max_length=1)),
                ('display_name', models.CharField(max_length=40)),
                ('is_detector_part', models.CharField(default='F', max_length=1)),
                ('extension_table_name', models.TextField(default='PARTS', max_length=30)),
                ('lpname', models.TextField(max_length=24)),
                ('is_record_deleted', models.CharField(default='F', max_length=1)),
                ('record_insertion_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('record_insertion_user', models.TextField(max_length=50)),
                ('record_lastupdate_time', models.DateTimeField()),
                ('record_lastupdate_user', models.TextField(max_length=50)),
                ('comment_description', models.TextField(max_length=4000)),
            ],
            options={
                'db_table': 'CMS_HGC_CORE_CONSTRUCT.KINDS_OF_PARTS',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Manufacturer',
            fields=[
                ('manufacturer_id', models.IntegerField(primary_key=True, serialize=False)),
                ('manufacturer_name', models.TextField(max_length=40)),
            ],
            options={
                'db_table': 'CMS_HGC_CORE_CONSTRUCT.MANUFACTURERS',
                'ordering': ('manufacturer_name',),
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Part',
            fields=[
                ('part_id', models.AutoField(primary_key=True, serialize=False)),
                ('name_label', models.TextField(blank=True, max_length=40, null=True)),
                ('serial_number', models.TextField(blank=True, max_length=40, null=True)),
                ('barcode', models.TextField(blank=True, max_length=40, null=True, unique=True)),
                ('version', models.TextField(blank=True, max_length=40, null=True)),
                ('installed_date', models.DateField(blank=True)),
                ('installed_by_user', models.TextField(blank=True, max_length=40, null=True)),
                ('removed_date', models.DateField(blank=True, null=True)),
                ('removed_by_user', models.TextField(blank=True, max_length=40, null=True)),
                ('extension_table_name', models.TextField(blank=True, max_length=30)),
                ('record_insertion_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('record_insertion_user', models.TextField(max_length=50)),
                ('record_lastupdate_time', models.DateTimeField()),
                ('record_lastupdate_user', models.TextField(max_length=50)),
                ('comment_description', models.TextField(blank=True, max_length=4000)),
                ('is_record_deleted', models.CharField(default='F', max_length=1)),
            ],
            options={
                'db_table': 'CMS_HGC_CORE_CONSTRUCT.PARTS',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Subdetector',
            fields=[
                ('subdetector_id', models.AutoField(primary_key=True, serialize=False)),
                ('subdetector_name', models.TextField(max_length=40)),
            ],
            options={
                'db_table': 'CMS_HGC_CORE_CONSTRUCT.SUBDETECTORS',
                'managed': False,
            },
            bases=(models.Model, base.models.Base),
        ),
    ]
